name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
        
      - name: Install dependencies and build websit
        run: |
          npm install
          npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_EMAIL: 756319278@qq.com
          COMMIT_MESSAGE: website deploy
